/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyJNIExample */

#ifndef _Included_MyJNIExample
#define _Included_MyJNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyJNIExample
 * Method:    sayHelloC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyJNIExample_sayHelloC
  (JNIEnv *, jclass);

/*
 * Class:     MyJNIExample
 * Method:    sayHelloCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyJNIExample_sayHelloCpp
  (JNIEnv *, jobject);

/*
 * Class:     MyJNIExample
 * Method:    sayHelloCppStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyJNIExample_sayHelloCppStatic
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
